apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fkauf0q23-go 
  janus-idp.io/tekton: fkauf0q23-go
  backstage.io/kubernetes-id: fkauf0q23-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fkauf0q23-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml